---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: git-data-pvc
  namespace: gitea-repo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 256Gi
  storageClassName: standard-rwo