baseurl = "http://replace-this-with-your-hugo-site.com/"
languageCode = "en-us"
title = "Hugo Creative Theme"
theme = "creative"

[params]

	# You can use Markdown syntax for urls [text](//url.to/source) for
	# most longer texts.

	# All icons using Fontawesome's icon font. Look at fortawesome.github.io/Font-Awesome/icons/
	# for more icons. The icons are represented by their corresponding
	# CSS class.

	# All projects of the portfolio are defined in their own files.
	# You can find example projects at 'exampleSite/data/projects'. Copy the 'projects'
	# folder into the 'data' directory at the root of this Hugo site.
	# For more informtion take a look at the README.

	# To provide some metadata for search engines feel free to add a few
    # information about you and your website.
	name = "Axel Magnuson"
	description = "Axel Magnuson writes software.  Sometimes the software seems like it's learning.  Maybe one day the software will write its own software, and Axel will be the proud papa."

	# The path must be relative to the static folder
	favicon = "favicon.ico"


	# Navigation
	[params.navigation]
		brand = "Axel Magnuson"

		[params.navigation.links]
			about     = "About"
			services  = "Services"
			portfolio = "Portfolio"
			contact   = "Contact"


	# Hero section
	[params.hero]
		# To change the background of the hero section, replace the 'header.jpg' at './static/img' with your own.
		slogan     = "Axel Magnuson"
		subtitle   = "I write software.  Sometimes the software seems like it's learning.  Maybe one day the software will write its own software, and I will be the proud papa."
		buttonText = "Okay..."


	# About section
	[params.about]
		headline    = "A Man of At Least a Couple Talents"
		description = """
I am a Software Engineer and a Data Scientist.  I build powerful products by
adhering to the Unix principle of small, sharp tools.  Most of the time these
are robust backend web services, implementing anything from business logic to
AI-based event detection.  I specialize in machine learning and big data
applications, but I have also worked extensively in web development.
        """
		# buttonText  = "Get Started!"


	# Service section
	[params.services]
		headline = "At your service"

        [[params.services.list]]
            icon = "fa-diamond"
            title = "Machine Learning"
            description = "Our templates are updated regularly so they don't break."

        [[params.services.list]]
			icon = "fa-paper-plane"
			title = "Big Data"
			description = "You can use this theme as is, or you can make changes!"

		[[params.services.list]]
            icon = "fa-newspaper-o"
            title = "Web Development"
            description = "We update dependencies to keep things fresh."

        [[params.services.list]]
            icon = "fa-heart"
            title = "DevOps"
            description = "You have to make your websites with love these days!"


    # Portfolio modals
	[params.portfolio.modal]
        client = "Client"
        date = "Date"
        category = "Category"
        buttonText = "Close"

    # Aside section
	[params.aside]
		headline = "Check out My Blog"

		[params.aside.button]
			text = "Download now"
			link = "//github.com/digitalcraftsman/hugo-creative-theme"

	# Contact section
	[params.contact]
		headline = "Let's Get In Touch!"
		description = "Ready to start your next project with us? That's great! Give us a call or send us an email and we will get back to you as soon as possible!"
		phone = "123-456-6789"
		email = "feedback@startbootstrap.com"
