baseurl = "http://replace-this-with-your-hugo-site.com/"
languageCode = "en-us"
title = "Axel Magnuson"
theme = "creative"

[params]

	# You can use Markdown syntax for urls [text](//url.to/source) for
	# most longer texts.

	# All icons using Fontawesome's icon font. Look at fortawesome.github.io/Font-Awesome/icons/
	# for more icons. The icons are represented by their corresponding
	# CSS class.

	# All projects of the portfolio are defined in their own files.
	# You can find example projects at 'exampleSite/data/projects'. Copy the 'projects'
	# folder into the 'data' directory at the root of this Hugo site.
	# For more informtion take a look at the README.

	# To provide some metadata for search engines feel free to add a few
    # information about you and your website.
	name = "Axel Magnuson"
	description = "Data Scientist // Web Developer"
	# description = "Axel Magnuson writes software.  Sometimes the software seems like it's learning.  Maybe one day the software will write its own software, and Axel will be the proud papa."

	# The path must be relative to the static folder
	favicon = "favicon.ico"


	# Navigation
	[params.navigation]
		brand = "Axel Magnuson"

		[params.navigation.links]
			about     = "About"
			services  = "Services"
			portfolio = "Portfolio"
			contact   = "Contact"


	# Hero section
	[params.hero]
		# To change the background of the hero section, replace the 'header.jpg' at './static/img' with your own.
		slogan     = "Axel Magnuson"
        # in the subtitle, give the "title" of what you're going to tell them.
        # subtitle = "A One-Stop Shop for Badass Software"
        subtitle = "Data Scientist // Web Developer"
		# subtitle   = "I write software.  Sometimes the software seems like it's learning.  Maybe one day the software will write its own software, and I will be the proud papa."
		buttonText = "Nice to meet you"


	# About section
    # Education, Experience, Projects. Tell them what you're going to tell them.
	[params.about]
        # headline = "A One-Stop Shop for Badass Software"
		headline    = "A Man of At Least a Couple Talents"
		description = """
I am a Computer Science M.Sc. with a background in mathematics and four years of
software development experience. I build powerful data products and web applications 
by adhering to the Unix principle of small, sharp tools.  

In the past I have worked on popularity prediction for social networks, radar
object classification and correlation, social network modeling, big data
processing pipelines, full stack web applications, and microservice
architectures. Sometimes I take leadership roles. I love working with data and
software systems, and I am always eager to find exciting projects that challenge
me to grow.
"""
		buttonText  = "Cool"


	# Service section
	[params.services]
		headline = "Things I Do"

        [[params.services.list]]
            icon = "fa-graduation-cap"
            title = "Data Science"
            description = "From predictive analytics to recommender systems.  Data nerd at your service."

		[[params.services.list]]
            icon = "fa-wrench"
            title = "Software Engineering"
            description = "Sooner or later, you need to create a great product. I can help with that."

        [[params.services.list]]
			icon = "fa-tachometer"
			title = "Big Data Solutions"
			description = "For managing volume, velocity, and variety."

        [[params.services.list]]
            icon = "fa-cogs"
            title = "Development Operations"
            description = "Good engineers need tools that support them."


    # Portfolio modals
	[params.portfolio.modal]
        client = "Client"
        date = "Year"
        category = "Category"
        buttonText = "Close"

    # Aside section
	[params.aside]
		headline = "I have a CV"

		[params.aside.button]
			text = "Check it out"
			link = "//cv.axelmagn.com"

	# Contact section
	[params.contact]
		headline = "Let's Get In Touch!"
		description = "Like what you see?  Drop me a line! I don't bite and I like meeting new people."
		phone = "+1 (208) 391 3928"
		email = "axelmagn@gmail.com"
